package com.example.arknightsautoclicker.processing.tasks.recruitment

import com.example.arknightsautoclicker.processing.ext.norm

// two CharTags are equal if they have the same name_norm
data class CharTag(
    val name: String,
    val rarity: Int,
    val tags: Set<String>,
    val priority: Int = 1
) {
    override fun equals(other: Any?) =
        other is CharTag && name_norm == other.name_norm
    override fun hashCode() = name_norm.hashCode()
    //lowercase, and only letters
    val name_norm = name.norm
    val tags_norm = tags.map { it.norm } .toSet()
}


private typealias C = CharTag
private inline fun <reified T> S(vararg elements: T) = HashSet<T>(elements.toList())

class TagData {
    val characters = S(
        C("Lancet-2", 1, S("Robot","Ranged","Healing","Medic","Female")),
        C("Castle-3", 1, S("Robot","Melee","Support","Guard","Male")),
        C("Yato", 2, S("Melee","Starter","Vanguard","Female")),
        C("Durin", 2, S("Ranged","Starter","Caster","Female")),
        C("12F", 2, S("Ranged","Starter","Caster","Male")),
        C("Rangers", 2, S("Ranged","Starter","Sniper","Male")),
        C("Noir Corne", 2, S("Melee","Starter","Defender","Male")),
        C("Fang", 3, S("Melee","DP-Recovery","Vanguard","Female")),
        C("Vanilla", 3, S("Melee","DP-Recovery","Vanguard","Female")),
        C("Plume", 3, S("Melee","DPS","DP-Recovery","Vanguard","Female")),
        C("Hibiscus", 3, S("Ranged","Healing","Medic","Female")),
        C("Ansel", 3, S("Ranged","Healing","Medic","Male")),
        C("Lava", 3, S("Ranged","AoE","Caster","Female")),
        C("Steward", 3, S("Ranged","DPS","Caster","Male")),
        C("Kroos", 3, S("Ranged","DPS","Sniper","Female")),
        C("Adnachiel", 3, S("Ranged","DPS","Sniper","Male")),
        C("Orchid", 3, S("Ranged","Slow","Supporter","Female")),
        C("Melantha", 3, S("Melee","DPS","Survival","Guard","Female")),
        C("Beagle", 3, S("Melee","Defense","Defender","Female")),
        C("Scavenger", 4, S("Melee","DP-Recovery","DPS","Vanguard","Female")),
        C("Vigna", 4, S("Melee","DPS","DP-Recovery","Vanguard","Female")),
        C("Myrrh", 4, S("Ranged","Healing","Medic","Female")),
        C("Perfumer", 4, S("Ranged","Healing","Medic","Female")),
        C("Haze", 4, S("Ranged","DPS","Debuff","Caster","Female")),
        C("Gitano", 4, S("Ranged","AoE","Caster","Female")),
        C("Gravel", 4, S("Melee","Fast-Redeploy","Defense","Specialist","Female")),
        C("Rope", 4, S("Melee","Shift","Specialist","Female")),
        C("Shaw", 4, S("Melee","Shift","Specialist","Female")),
        C("ShiraYuki", 4, S("Ranged","AoE","Slow","Sniper","Female")),
        C("Meteor", 4, S("Ranged","DPS","Debuff","Sniper","Female")),
        C("Jessica", 4, S("Ranged","DPS","Survival","Sniper","Female")),
        C("Earthspirit", 4, S("Ranged","Slow","Supporter","Female")),
        C("Dobermann", 4, S("Melee","DPS","Support","Guard","Female")),
        C("Estelle", 4, S("Melee","AoE","Survival","Guard","Female")),
        C("Beehunter", 4, S("Melee","DPS","Guard","Female")),
        C("Mousse", 4, S("Melee","DPS","Guard","Female")),
        C("Frostleaf", 4, S("Melee","Slow","DPS","Guard","Female")),
        C("Matoimaru", 4, S("Melee","Survival","DPS","Guard","Female")),
        C("Cuora", 4, S("Melee","Defense","Defender","Female")),
        C("Гум", 4, S("Melee","Defense","Healing","Defender","Female")),
        C("Matterhorn", 4, S("Melee","Defense","Defender","Male")),
        C("Texas", 5, S("Senior Operator","Melee","DP-Recovery","Crowd Control","Vanguard","Female")),
        C("Зима", 5, S("Senior Operator","Melee","DP-Recovery","Support","Vanguard","Female")),
        C("Ptilopsis", 5, S("Senior Operator","Ranged","Healing","Support","Medic","Female")),
        C("Silence", 5, S("Senior Operator","Ranged","Healing","Medic","Female")),
        C("Warfarin", 5, S("Senior Operator","Ranged","Healing","Support","Medic","Female")),
        C("Nightmare", 5, S("Senior Operator","Ranged","DPS","Healing","Slow","Caster","Female")),
        C("Projekt Red", 5, S("Senior Operator","Melee","Fast-Redeploy","Crowd Control","Specialist","Female")),
        C("Manticore", 5, S("Senior Operator","Melee","DPS","Survival","Specialist","Female")),
        C("Cliffheart", 5, S("Senior Operator","Melee","Shift","DPS","Specialist","Female")),
        C("FEater", 5, S("Senior Operator","Melee","Shift","Slow","Specialist","Female")),
        C("Provence", 5, S("Senior Operator","Ranged","DPS","Sniper","Female")),
        C("Blue Poison", 5, S("Senior Operator","Ranged","DPS","Sniper","Female")),
        C("Firewatch", 5, S("Senior Operator","Ranged","DPS","Nuker","Sniper","Female")),
        C("Meteorite", 5, S("Senior Operator","Ranged","AoE","Debuff","Sniper","Female")),
        C("Platinum", 5, S("Senior Operator","Ranged","DPS","Sniper","Female")),
        C("Pramanix", 5, S("Senior Operator","Ranged","Debuff","Supporter","Female")),
        C("Истина", 5, S("Senior Operator","Ranged","Slow","DPS","Supporter","Female")),
        C("Mayer", 5, S("Senior Operator","Ranged","Summon","Crowd Control","Supporter","Female")),
        C("Specter", 5, S("Senior Operator","Melee","AoE","Survival","Guard","Female")),
        C("Indra", 5, S("Senior Operator","Melee","DPS","Survival","Guard","Female")),
        C("Ch'en", 6, S("Top Operator","Melee","Nuker","DPS","Guard","Female")),
        C("Nearl", 5, S("Senior Operator","Melee","Defense","Healing","Defender","Female")),
        C("Liskarm", 5, S("Senior Operator","Melee","Defense","DPS","Defender","Female")),
        C("Vulcan", 5, S("Senior Operator","Melee","Survival","Defense","DPS","Defender","Female")),
        C("Croissant", 5, S("Senior Operator","Melee","Defense","Shift","Defender","Female")),
        C("Siege", 6, S("Top Operator","Melee","DP-Recovery","DPS","Vanguard","Female")),
        C("Shining", 6, S("Top Operator","Ranged","Healing","Support","Medic","Female")),
        C("Nightingale", 6, S("Top Operator","Ranged","Healing","Support","Medic","Female")),
        C("Ifrit", 6, S("Top Operator","Ranged","AoE","Debuff","Caster","Female")),
        C("Exusiai", 6, S("Top Operator","Ranged","DPS","Sniper","Female")),
        C("SilverAsh", 6, S("Top Operator","Melee","DPS","Support","Guard","Male")),
        C("Hoshiguma", 6, S("Top Operator","Melee","Defense","DPS","Defender","Female")),
        C("Saria", 6, S("Top Operator","Melee","Defense","Healing","Support","Defender","Female")),
        C("Catapult", 3, S("Ranged","AoE","Sniper","Female"), priority = -1),
        C("Popukar", 3, S("Melee","AoE","Survival","Guard","Female"), priority = -1),
        C("Midnight", 3, S("Melee","DPS","Guard","Male")),
        C("Skadi", 6, S("Top Operator","Melee","DPS","Survival","Guard","Female")),
        C("Swire", 5, S("Senior Operator","Melee","DPS","Support","Guard","Female")),
        C("Spot", 3, S("Melee","Defense","Healing","Defender","Male")),
        C("Greyy", 4, S("Ranged","AoE","Slow","Caster","Male")),
        C("Schwarz", 6, S("Top Operator","Ranged","DPS","Sniper","Female")),
        C("Glaucus", 5, S("Senior Operator","Ranged","Slow","Crowd Control","Supporter","Female")),
        C("Sussurro", 4, S("Ranged","Healing","Medic","Female")),
        C("Myrtle", 4, S("Melee","DP-Recovery","Healing","Vanguard","Female")),
        C("Astesia", 5, S("Senior Operator","Melee","DPS","Defense","Guard","Female")),
        C("Hellagur", 6, S("Top Operator","Melee","DPS","Survival","Guard","Male")),
        C("Vermeil", 4, S("Ranged","DPS","Sniper","Female")),
        C("Magallan", 6, S("Top Operator","Ranged","Support","Slow","DPS","Supporter","Female")),
        C("Executor", 5, S("Senior Operator","Ranged","AoE","Sniper","Male")),
        C("Waai Fu", 5, S("Senior Operator","Melee","Fast-Redeploy","Debuff","Specialist","Female")),
        C("Mostima", 6, S("Top Operator","Ranged","AoE","Support","Crowd Control","Caster","Female")),
        C("May", 4, S("Ranged","DPS","Slow","Sniper","Female")),
        C("Reed", 5, S("Senior Operator","Melee","DP-Recovery","DPS","Vanguard","Female")),
        C("Broca", 5, S("Senior Operator","Melee","AoE","Survival","Guard","Male")),
        C("Ambriel", 4, S("Ranged","DPS","Slow","Sniper","Female")),
        C("GreyThroat", 5, S("Senior Operator","Ranged","DPS","Sniper","Female")),
        C("Blaze", 6, S("Top Operator","Melee","DPS","Survival","Guard","Female")),
        C("Aak", 6, S("Top Operator","Ranged","Support","DPS","Specialist","Male")),
        C("Hung", 5, S("Senior Operator","Melee","Defense","Healing","Defender","Male")),
        C("Ceobe", 6, S("Top Operator","Ranged","DPS","Crowd Control","Caster","Female")),
        C("Leizi", 5, S("Senior Operator","Ranged","DPS","Caster","Female")),
        C("Purestream", 4, S("Ranged","Healing","Support","Medic","Female")),
        C("Bagpipe", 6, S("Top Operator","Melee","DP-Recovery","DPS","Vanguard","Female")),
        C("Sesa", 5, S("Senior Operator","Ranged","AoE","Debuff","Sniper","Male")),
        C("Utage", 4, S("Melee","DPS","Survival","Guard","Female")),
        C("Phantom", 6, S("Top Operator","Melee","Fast-Redeploy","Crowd Control","DPS","Specialist","Male")),
        C("Shamare", 5, S("Senior Operator","Ranged","Debuff","Supporter","Female")),
        C("Cutter", 4, S("Melee","Nuker","DPS","Guard","Female")),
        C("Thermal-EX", 1, S("Robot","Melee","Nuker","Specialist","Male")),
        C("Weedy", 6, S("Top Operator","Melee","Shift","DPS","Crowd Control","Specialist","Female")),
        C("Elysium", 5, S("Senior Operator","Melee","DP-Recovery","Support","Vanguard","Male")),
        C("Asbestos", 5, S("Senior Operator","Melee","Defense","DPS","Defender","Female")),
        C("Tsukinogi", 5, S("Senior Operator","Ranged","Support","Survival","Supporter","Female")),
        C("Podenco", 4, S("Ranged","Slow","Healing","Supporter","Female")),
        C("Leonhardt", 5, S("Senior Operator","Ranged","AoE","Nuker","Caster","Male")),
        C("Роса", 6, S("Top Operator","Ranged","DPS","Crowd Control","Sniper","Female")),
        C("\"Justice Knight\"", 1, S("Robot","Ranged","Support","Sniper","Female"))
    )
}
